### ISSUE TITLE
Feature Request: add text highlight customized function

### ISSUE THREAD

**Issue by xujialiu** [adrianlyjak/obsidian-aloud-tts#39]
This is a great Obsidian plugin, but the highlight colors for the text being read and the text not yet read are too similar. Could you add an extra configuration option in the settings or an additional configuration JSON file to set the highlight RGBA values? 

Thank you very much.

**Comment by adrianlyjak** [comment]
Yeah, those could be improved. Its currently "40% purple" for the active sentence, and "20% purple" for the rest of the player selection. 

You customize the colors with a css snippet (built into obsidian), just put a css file in `<vault>/.obsidian/snippets`, and load it in Appearance > Snippets.

```css
.tts-cm-playing-before,
.tts-cm-playing-after {
  background-color: rgba(var(--color-red-rgb), 0.5) !important;
}

.tts-cm-playing-now {
  background-color: rgba(var(--color-blue-rgb), 0.5) !important;
}
```

shows red and blue 👇 

<img width="573" alt="image" src="https://github.com/adrianlyjak/obsidian-aloud-tts/assets/2024018/01b249c3-b988-4b7a-8f23-759f2c43d89c">

What colors were you thinking? Perhaps there could be better defaults, I didn't think too hard about it
